### ISSUE TITLE
stop -> start sometimes results in crashed syslog service.

### ISSUE THREAD

**Issue by GenTarkin** [StuartIanNaylor/zram-config#25]
I happened to notice that about half the time when running the "stop -> start" commands to restart zram-config ... it results the syslog service being a "red" state and not running. Manually starting syslog seems to fix it sometime later.
I believe the syslog start / stop commands u have in the script are not working as intended. I can run the same command to stop syslog, but it always respawns on its own nearly instantaneously.

**Comment by StuartIanNaylor** [comment]
Think mstormi fixed that
