### ISSUE TITLE
Confused about page-cache setting

### ISSUE THREAD

**Issue by wanton7** [StuartIanNaylor/zram-config#38]
I'm no Linux expert and I tried to search information about page-cache setting that you mention in README.md and at https://github.com/StuartIanNaylor/zram-config/tree/master/swap-performance .
But I couldn't find any setting named like that by googling. How do I set page-cache to 0 in Ubuntu?

**Comment by StuartIanNaylor** [comment]
Already does it for you in the ztab
```
# swap	alg	mem_limit	disk_size	swap_priority	page-cluster	swappiness
swap	lz4	250M		750M		75		0		80
```
page_cluster is set to 0 by default.

**Comment by wanton7** [comment]
Ok thanks, I didn't understand page-cache settings means vm.pagecluster. From reading documents about it, I thought it only effects reads from swap not page writes.
