### ISSUE TITLE
Question: Does zram-config work together with fail2ban?

### ISSUE THREAD

**Issue by smokemyshoes** [StuartIanNaylor/zram-config#43]
Hi

Maybe a totall noob question but nevertheless.... Will fail2ban work after using log2ram?

If yes, will it require any (re-)configuration of fail2ban?

Many thanks in advance!

**Comment by StuartIanNaylor** [comment]
I guess its just the service order and that fail2ban should start after zram-config as that means it will close before and not create log locks on shutdown.

But answer is without trying there should be no reason why not as the logs still retain the same path but are on a bind mount.
If you have any problems maybe edit the service and put zram-config in the after section of the of the fail2ban service.

**Comment by smokemyshoes** [comment]
Thanks. I'll give it a try.
